variables: 
 JAVA_TO_BUILD: jdk11u

name: "AdoptOpenJDK-$(JAVA_TO_BUILD)-$(Date:yyyy-MM-dd)"

trigger: none

pr: none

stages:
#  - template: ./build/build.yml
  - stage: test_macOS_x64_hotspot_binaries
    variables:
      ADOPT_TEST_REPO_URI: 'https://github.com/AdoptOpenJDK/openjdk-tests'
      ADOPT_TEST_REPO_BRANCH: 'master'
    jobs:
      # - template: ./tkg/openjdk/sanity.yml
      #   parameters:
      #     pool:
      #       vmImage: macOS-10.14
      - template: ./test/functional/sanity.yml
        parameters:
          pool:
            vmImage: macOS-10.14
