parameters:
  buildList: "openjdk"
  testTarget: "_sanity.openjdk"
  failTaskOnTestFailures: true
  testResultSearchPath: "**/*.jtr.xml"
  pool: {}
  useContainer: {}

jobs:
  - job: openjdk_sanity
    displayName: "OpenJDK Sanity Check"
    variables:
      BUILD_LIST: ${{ parameters.buildList }}
      TEST_TARGET: ${{ parameters.testTarget }}
      FAIL_TASK_ON_FAILED_TESTS: ${{ parameters.failTaskOnTestFailures }}
      TEST_RESULT_SEARCH_PATH: ${{ parameters.testResultSearchPath }}
    pool: ${{ parameters.pool }}
    ${{ insert }}: ${{ parameters.useContainer }}

    steps:
      - template: ./pre.yml
      - template: ../test_steps.yml